const featureProductsData=[
    {
        label:19,
        imageBefore:'https://themes.muffingroup.com/betheme-store/wp-content/uploads/2021/09/bethemestore-product-pic16-800x800.webp',
        imageAfter:'https://themes.muffingroup.com/betheme-store/wp-content/uploads/2021/09/bethemestore-product-pic16-800x800.webp',
        title:'BeHeadphones',
        originalPrice:'99.90',
        afterDiscountPrice:'85.90',
        stock:false,
    },
    {
        imageBefore:'https://themes.muffingroup.com/betheme-store/wp-content/uploads/2021/09/bethemestore-product-pic17-800x800.webp',
        imageAfter:'https://themes.muffingroup.com/betheme-store/wp-content/uploads/2021/09/bethemestore-product-pic17-1.webp',
        title:'BeHeadphones',
        afterDiscountPrice:'250.00',
        rating:3,
        stock:true,
    },
    {
        imageBefore:'https://themes.muffingroup.com/betheme-store/wp-content/uploads/2021/09/bethemestore-product-pic6-800x800.webp',
        imageAfter:'https://themes.muffingroup.com/betheme-store/wp-content/uploads/2021/09/bethemestore-product-pic6-1.webp',
        title:'BeHeadphones',
        afterDiscountPrice:'250.00',
        rating:5,
        stock:true
    },
    {
        label:25,
        imageBefore:'https://themes.muffingroup.com/betheme-store/wp-content/uploads/2021/09/bethemestore-product-pic5-800x800.webp',
        imageAfter:'https://themes.muffingroup.com/betheme-store/wp-content/uploads/2021/09/bethemestore-product-pic5-800x800.webp',
        title:'BeHeadphones',
        afterDiscountPrice:'225.00',
        rating:5,
        stock:true
    },
    {
        imageBefore:'https://themes.muffingroup.com/betheme-store/wp-content/uploads/2021/09/bethemestore-product-pic11-800x800.webp',
        imageAfter:'https://themes.muffingroup.com/betheme-store/wp-content/uploads/2021/09/bethemestore-product-pic11-1-800x800.webp',
        title:'BeHeadphones',
        originalPrice:'99.90',
        afterDiscountPrice:'85.90',
        rating:5,
        stock:true   
     },
    {
        label:25,
        imageBefore:'https://themes.muffingroup.com/betheme-store/wp-content/uploads/2021/09/bethemestore-product-pic12-800x800.webp',
        imageAfter:'https://themes.muffingroup.com/betheme-store/wp-content/uploads/2021/09/bethemestore-product-pic12-1.webp',
        title:'BeHeadphones',
        originalPrice:'99.90',
        afterDiscountPrice:'85.90',
        stock:false
    },
    {
        label:17,
        imageBefore:'https://themes.muffingroup.com/betheme-store/wp-content/uploads/2021/09/bethemestore-product-pic15-800x800.webp',
        imageAfter:'https://themes.muffingroup.com/betheme-store/wp-content/uploads/2021/09/bethemestore-product-pic15-1.webp',
        title:'BeHeadphones',
        originalPrice:'99.90',
        afterDiscountPrice:'85.90',
        rating:5,
        stock:false
    },
    {
        label:29,
        imageBefore:'https://themes.muffingroup.com/betheme-store/wp-content/uploads/2021/09/bethemestore-product-pic3-800x800.webp',
        imageAfter:'https://themes.muffingroup.com/betheme-store/wp-content/uploads/2021/09/bethemestore-product-pic3-1-800x800.webp',
        title:'BeHeadphones',
        originalPrice:'140.00',
        afterDiscountPrice:'99.00',
        rating:4,
        stock:true
    }
]


export default featureProductsData;